Restaurant-Website/Models/Menu/ProductCategoryViewModel.cs
using System.Collections.Generic;

namespace Restaurant_Website.Models.Menu
{
    public class ProductCategoryViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int? ImageId { get; set; }
        public IEnumerable<ProductViewModel> Products { get; set; }
    }
}

Restaurant-Website/Models/Menu/ProductViewModel.cs
namespace Restaurant_Website.Models.Menu
{
    public class ProductViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public int? ImageId { get; set; }
        public int? CategoryId { get; set; }
    }
}

Restaurant-Website/Controllers/MenuController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Restaurant_Website.Services.Interfaces;
using AutoMapper;
using Restaurant_Website.Domain.Core;
using Restaurant_Website.Models.Menu;
using System.Linq;
using Microsoft.AspNetCore.Http;
using System.Collections.Generic;

namespace Restaurant_Website.Controllers
{
    public class MenuController : Controller
    {
        private readonly IUploadFileService uploadFileService;
        private readonly IProductCategoryService productCategoryService;
        private readonly string userLanguage; 

        public MenuController(IUploadFileService uploadFileService, IProductCategoryService productCategoryService, IHttpContextAccessor accessor)
        {
            this.uploadFileService = uploadFileService;
            this.productCategoryService = productCategoryService;

            this.userLanguage = accessor.HttpContext.Request.Cookies["culture"] ?? accessor.HttpContext.Items["culture"].ToString();
        }

        public async Task<IActionResult> GetImage(int? id)
        {
            if (!id.HasValue) return NotFound();

            var img = await uploadFileService.GetByIdAsync(id.Value);

            if (img is null) return NotFound();
            else return new FileContentResult(img.Content, img.ContentType);
        }

        [HttpPost]
        public async Task<IActionResult> GetProducts(int categoryId)
        {
            var category = await productCategoryService.GetCategoryByIdAsync(categoryId);
            
            if (!(category is null))
            {
                IMapper productMapper = new MapperConfiguration(cfg => cfg.CreateMap<Product, ProductViewModel>()
                                            .ForMember(m => m.Name, opt => opt.MapFrom((s, d) => d.Name = s.Translations.First(t => t.Language.Code == userLanguage).Name))
                                            .ForMember(m => m.Description, opt => opt.MapFrom((s, d) => d.Description = s.Translations.First(t => t.Language.Code == userLanguage).Description)))
                                            .CreateMapper();

                var products = productMapper.Map<IEnumerable<ProductViewModel>>(category.Products);

                return PartialView("CategoryProducts", products);

            }
            else
                return NotFound();
        }

        [Route("menu")]
        public async Task<ViewResult> Index()
        {
            var categories = await productCategoryService.GetProductCategoriesAsync();

            IMapper mapper = new MapperConfiguration(cfg => {
                cfg.CreateMap<Product, ProductViewModel>()
                                            .ForMember(m => m.Name, opt => opt.MapFrom((s, d) => d.Name = s.Translations.First(t => t.Language.Code == userLanguage).Name))
                                            .ForMember(m => m.Description, opt => opt.MapFrom((s, d) => d.Description = s.Translations.First(t => t.Language.Code == userLanguage).Description));
                cfg.CreateMap<ProductCategory, ProductCategoryViewModel>()
                    .ForMember(m => m.Name, opt => opt.MapFrom((s, d) => d.Name = s.Translations.First(t => t.Language.Code == userLanguage).Name));
            }).CreateMapper();

            var model = mapper.Map<IEnumerable<ProductCategoryViewModel>>(categories);
            return View(model);
        }
    }
}

Restaurant-Website/Views/Menu/CategoryProducts.cshtml
<!-- Partial view -->

@model IEnumerable<ProductViewModel>


<div class="u-expanded-width u-products u-products-1">
    <div class="u-list u-repeater u-list-1">
        <div class="u-container-style u-list-item u-repeater-item">
            @foreach (var product in Model)
            {
                <form asp-controller="Cart" asp-action="AddToCart" method="post" data-ajax="true" data-ajax-method="post" data-ajax-mode="replace" data-ajax-update="#userCartContent">
                    <div class="u-container-layout u-similar-container u-valign-top u-container-layout-1">
                        <img src="@Url.Action("GetImage", "Menu", new { id = product.ImageId })" alt="" class="u-expanded-width u-image u-image-default u-image-1" />
                        <h5 class="u-text u-text-1">@product.Name&nbsp;</h5>
                        <p class="u-text u-text-2">@product.Description</p>
                        <h4 class="u-text u-text-black u-text-3">$ @product.Price</h4>

                        <button type="submit" name="productId" value="@product.Id" class="u-black u-btn u-button-style u-btn-2">BUY</button>
                        <input style="width: 20%;" class="u-quantity-input u-product-quantity u-text u-text-4" type="number" name="count" value="1" min="1" />
                    </div>
                </form>
            }
        </div>
    </div>
</div>

Restaurant-Website/Views/Menu/Index.cshtml
@{
    Layout = "_Layout";
}

@model IEnumerable<Restaurant_Website.Models.Menu.ProductCategoryViewModel>

<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.min.js"></script>

<link rel="stylesheet" href="~/css/Menu.css" />

<section class="u-clearfix u-white u-section-1" id="carousel_3729">
    <div class="u-clearfix u-sheet u-sheet-1">
        <div id="outer" class="btn-group">

            <form asp-controller="Menu" asp-action="GetProducts" method="post" data-ajax="true" data-ajax-method="post" data-ajax-mode="replace" data-ajax-update="#menuProducts" data-ajax-loading="#whileLoading">
                @foreach (var item in Model)
                {
                    <button type="submit" name="categoryId" value="@item.Id" style="margin-right: 10px" class="inner u-btn u-btn-round u-button-style u-hover-palette-1-light-1 u-palette-1-base u-radius-11 u-btn-1">
                        @item.Name
                    </button>
                }
            </form>
            <div id="menuProducts">
                @await Html.PartialAsync("CategoryProducts", Model.SelectMany(t => t.Products));
            </div>
        </div>
        <div id="whileLoading" class="loader" style="margin-left: 50%; display: none"></div>
        <div id="userCartContent"></div>

        @if (User.Identity.IsAuthenticated)
        {
            @await Html.PartialAsync("CartIcon")
        }
    </div>
</section>